allowBuilds:
  '@parcel/watcher': true
  core-js: true
  core-js-pure: true
  esbuild: true
  vue-demi: true
nodeLinker: hoisted
onlyBuiltDependencies:
  - esbuild
  - vue-demi
  - '@parcel/watcher'
  - core-js
  - core-js-pure
